global:
  evaluation_interval: 10s
  scrape_interval: 1s
storage:
  tsdb:
    out_of_order_time_window: 30m
scrape_configs:
- job_name: otel-collector
  static_configs:
  - targets:
    - 'otel-col:8888'
rule_files:
  - "alert-rules.yaml"